# Generated by Django 4.0.5 on 2022-07-08 11:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import freelancer.job.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان دسته')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='آدرس دسته')),
                ('status', models.BooleanField(default=True, verbose_name='فعال شود ؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='job.category', verbose_name='زیردسته')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پروژه')),
                ('company_name', models.CharField(blank=True, default='شخصی', max_length=100, null=True, verbose_name='اسم شرکت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default=None, max_length=120, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=10, verbose_name='مهارت های مورد نیاز')),
                ('description', django_quill.fields.QuillField(max_length=20000, verbose_name='توضیحات جاب')),
                ('place', models.CharField(max_length=100, verbose_name='مکان')),
                ('work_type', models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('teleworking', 'دور کاری'), ('internship', 'کاراموز'), ('temporary', 'موقت')], max_length=30, verbose_name='نوع همکاری')),
                ('image', models.ImageField(blank=True, null=True, upload_to=freelancer.job.models.image_job_directory_path, verbose_name='عکس پروژه یا لوگو شرکت')),
                ('experience', models.CharField(blank=True, default='مهم نیست', max_length=30, null=True, verbose_name='سابقه کار')),
                ('salary', models.CharField(max_length=100, verbose_name='حقوق در نظر گرفته شده')),
                ('gender', models.CharField(choices=[('no_matter', 'مهم نیست'), ('man', 'اقا'), ('femail', 'خانوم')], max_length=30, verbose_name='جنسیت')),
                ('military_status', models.CharField(choices=[('end_Soldeir', 'پایان خدمت'), ('soldier', 'در حال انجام'), ('exempt', 'معافیت'), ('included', 'مشمول'), ('no_matter', 'مهم نیست')], max_length=30, verbose_name='نظام وظیفه')),
                ('educational_level', models.CharField(choices=[('no_matter', 'مهم نیست'), ('diploma', 'دیپلم'), ('lisanse', 'لیسانس'), ('mastersdegree', 'فوق لیسانس'), ('phd', 'دکترا و بالاتر')], max_length=30, verbose_name='مدرک تحصیلی')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت این اگهی')),
                ('urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('highlight', models.BooleanField(default=False, verbose_name='برجسته')),
                ('private', models.BooleanField(default=False, verbose_name='محرمانه')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='job.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'پذیرفته شد'), ('reject', 'رد شد'), ('wait', 'در حال انتظار')], default='wait', max_length=20, verbose_name='وضعیت درخواست')),
                ('created', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applay', to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_applay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
