# Generated by Django 4.0.5 on 2022-07-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='price',
        ),
        migrations.AddField(
            model_name='apply',
            name='bid_amount',
            field=models.CharField(default=0, max_length=100, verbose_name='مبلغ پیشنهادی'),
        ),
        migrations.AddField(
            model_name='apply',
            name='bid_date',
            field=models.IntegerField(default=0, verbose_name='زمان انجام پروژه'),
        ),
        migrations.AlterField(
            model_name='job',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده؟'),
        ),
    ]
