# Generated by Django 4.0.5 on 2022-06-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, default='شخصی', max_length=100, null=True, verbose_name='اسم شرکت'),
        ),
    ]
