# Generated by Django 4.0.5 on 2022-07-07 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='military_status',
            field=models.CharField(choices=[('end_Soldeir', 'پایان خدمت'), ('soldier', 'سرباز'), ('exempt', 'معافیت'), ('no_matter', 'مهم نیست')], max_length=30, verbose_name='نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='job',
            name='place',
            field=models.CharField(max_length=100, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=10, verbose_name='مهارت های مورد نیاز'),
        ),
    ]
