# Generated by Django 4.0.5 on 2022-07-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_experience_alter_job_description_alter_job_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('teleworking', 'دور کاری'), ('internship', 'کاراموز'), ('temporary', 'موقت')], max_length=30, verbose_name='نوع همکاری'),
        ),
    ]
