# Generated by Django 4.0.5 on 2022-07-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_apply_finish_time_remove_apply_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات برای کارفرما'),
        ),
    ]
