# Generated by Django 4.0.5 on 2022-06-29 12:43

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
