# Generated by Django 4.0.5 on 2022-06-29 12:48

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_editorjs_fields.fields.EditorJsTextField(max_length=3000, verbose_name='توضیحات پروژه'),
        ),
    ]
