# Generated by Django 4.0.5 on 2022-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerscomment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
