# Generated by Django 4.0.5 on 2022-07-27 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_alter_employerscomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='applyproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apply_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('apply_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='project.applyproject', verbose_name='پروژه مربوط به پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_conversation_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده پیام')),
            ],
        ),
    ]
