# Generated by Django 4.0.5 on 2022-07-22 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_alter_employerscomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='applyproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_apply_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
