# Generated by Django 4.0.5 on 2022-07-04 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='مبلغ(ریال)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('authority', models.CharField(max_length=120, verbose_name='توکن خرید')),
                ('payed', models.BooleanField(default=False, verbose_name='پرداخت شده ؟')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_pay', to='job.job', verbose_name='جاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_pay', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'Job Payment',
                'verbose_name_plural': 'Job Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='مبلغ(ریال)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('authority', models.CharField(max_length=120, verbose_name='توکن خرید')),
                ('payed', models.BooleanField(default=False, verbose_name='پرداخت شده ؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_pay', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
            },
        ),
    ]
