# Generated by Django 4.0.5 on 2022-10-05 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_conversation_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=120, verbose_name='توکن خرید')),
                ('paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('card_pan', models.CharField(max_length=30, verbose_name='شماره کارت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('price', models.IntegerField(verbose_name='مبلغ(ریال)')),
                ('ref_id', models.IntegerField(verbose_name='شماره تراکنش')),
                ('fee', models.IntegerField(verbose_name='کارمزد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payer', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
            },
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=120, verbose_name='توکن خرید')),
                ('paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('card_pan', models.CharField(max_length=30, verbose_name='شماره کارت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('price', models.IntegerField(verbose_name='مبلغ(ریال)')),
                ('ref_id', models.IntegerField(verbose_name='شماره تراکنش')),
                ('fee', models.IntegerField(verbose_name='کارمزد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_project', to='project.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_payer', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'Project Payment',
                'verbose_name_plural': 'Projects Payments',
            },
        ),
        migrations.RemoveField(
            model_name='paymentproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymentproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentAccount',
        ),
        migrations.DeleteModel(
            name='PaymentProject',
        ),
    ]
