# Generated by Django 4.0.5 on 2022-10-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0002_accountpayment_projectpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=120, verbose_name='توکن خرید')),
                ('paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('card_pan', models.CharField(max_length=30, verbose_name='شماره کارت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('object_id', models.PositiveIntegerField()),
                ('price', models.IntegerField(verbose_name='مبلغ(ریال)')),
                ('ref_id', models.IntegerField(verbose_name='شماره تراکنش')),
                ('fee', models.IntegerField(verbose_name='کارمزد')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payer', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
            },
        ),
        migrations.RemoveField(
            model_name='projectpayment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountPayment',
        ),
        migrations.DeleteModel(
            name='ProjectPayment',
        ),
    ]
