# Generated by Django 4.0.5 on 2022-07-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentjob',
            old_name='payed',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='paymentproject',
            old_name='payed',
            new_name='paid',
        ),
    ]
