# Generated by Django 4.0.5 on 2022-10-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0003_payment_remove_projectpayment_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payments', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ایدی پرداختی مرتبط'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='contenttypes.contenttype', verbose_name='پرداختی برای'),
        ),
    ]
