# Generated by Django 4.0.5 on 2022-07-13 17:59

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_quill.fields.QuillField(max_length=20000, verbose_name='جواب سوال'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='position',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='یک عدد صحیح برای مرتب کردن سوال در میان سایر سوالات'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=100, verbose_name='متن سوال'),
        ),
    ]
