# Generated by Django 4.0.5 on 2022-07-20 10:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepricingpanel',
            name='active_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_pricing_panel', to='pricing.pricingpanel', verbose_name='پنل فعال'),
        ),
        migrations.AlterField(
            model_name='activepricingpanel',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 10, 29, 24, 257445, tzinfo=utc), verbose_name='تاریخ انقضای پنل'),
        ),
        migrations.AlterField(
            model_name='activepricingpanel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pricing_panel', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='pricingpanel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت پنل به ریال'),
        ),
    ]
