# Generated by Django 4.0.5 on 2022-07-23 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepricingpanel',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 18, 38, 27, 63545, tzinfo=utc), verbose_name='تاریخ انقضای پنل'),
        ),
    ]
