# Generated by Django 4.0.5 on 2022-07-30 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_activepricingpanel_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepricingpanel',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 13, 36, 56, 826444, tzinfo=utc), verbose_name='تاریخ انقضای پنل'),
        ),
    ]
