# Generated by Django 4.0.5 on 2022-10-07 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_activepricingpanel_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activepricingpanel',
            old_name='count',
            new_name='apply_counter',
        ),
        migrations.RenameField(
            model_name='pricingpanel',
            old_name='count',
            new_name='apply_count',
        ),
        migrations.AlterField(
            model_name='activepricingpanel',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 12, 32, 55, 312835, tzinfo=utc), verbose_name='تاریخ انقضای پنل'),
        ),
    ]
