# Generated by Django 4.0.5 on 2022-10-08 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_rename_count_activepricingpanel_apply_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepricingpanel',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 9, 3, 44, 602483, tzinfo=utc), verbose_name='تاریخ انقضای پنل'),
        ),
    ]
