# Generated by Django 4.0.5 on 2022-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='حرفه ای که کار میکنید'),
        ),
    ]
