# Generated by Django 4.0.5 on 2022-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_cv_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='summary',
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان و سمت'),
        ),
    ]
