# Generated by Django 4.0.5 on 2022-07-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
